config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/admin/sign_in')
  #devise_for :admins
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    #get 'dashboard', controller: 'admin/user_permissions'
    get 'dashboard' => 'dashboard#index'
    resources :roles
    resources :services
    resources :pages
    scope '/service' do
      resources :categories
      resources :bundles
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
     #resources :roles

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/pages/edit.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      editar pagina
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @page, url: {action: "update"}, html:{role: "form"} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Url</label>
                <%= f.text_field :url, autofocus: false, class: "form-control" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Titulo</label>
                <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Titulo" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Sub Titulo</label>
                <%= f.text_field :subtitle, class: "form-control", placeholder: "Sub titulo" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso uno</label>
                <%= f.text_field :paso_one, class: "form-control", placeholder: "Paso uno" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso dos</label>
                <%= f.text_field :paso_two, class: "form-control", placeholder: "Paso dos" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso tres</label>
                <%= f.text_field :paso_tree, class: "form-control", placeholder: "Paso tres" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Servicio</label>
                  <%= f.collection_select(:service_id, Service.all, :id, :name) %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paquete</label>
                  <%= f.collection_select(:bundle_id, Bundle.all, :id, :name) %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Activo</label>
                  <%= f.select(:visibility, [['SI', true], ['NO', false]]) %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/pages/index.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Todas las paginas
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"></h3>
            <div class="box-tools">
              <div class="input-group" style="width: 150px;">
                <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div><!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tbody><tr>
                <th>url</th>
                <th>titulo</th>
                <th>Sub-titulo</th>
                <th>paso uno</th>
                <th>paso dos</th>
                <th>paso 3</th>
                <th>activo</th>
                <th>servico</th>
                <th>paquete</th>
                <th>creado</th>
              </tr>
              <% @pages.each do |page| %>
                <tr>
                  <td><%= page.url %></td>
                  <td><%= page.title %></td>
                  <td><%= page.subtitle %></td>
                  <td><%= page.paso_one %></td>
                  <td><%= page.paso_two %></td>
                  <td><%= page.paso_tree %></td>
                  <td><%= page.visibility %></td>
                  <% if page.service.nil? %>
                    <td></td>
                  <%else%>
                  <td><%= page.service.name %></td>
                  <%end%>
                  <% if page.bundle.nil? %>
                    <td></td>
                  <%else%>
                  <td><%= page.bundle.name %></td>
                  <%end%>
                  <td><%= page.created_at.httpdate.to_date %></td>
                  <td>
                    <%= link_to edit_admin_page_path(page) do %>
                      <i class="fa fa-edit"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to admin_page_path(page), method: :delete,
                   data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-remove"></i>
                   <%end%>
                   </td>
                  <!--td><span class="label label-success">Approved</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td-->
                </tr>
              <%end%>
            </tbody></table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/pages/new.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Nuevo Paquete
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @page, url: {action: "create"}, html:{role: "form"} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Url</label>
                <%= f.text_field :url, autofocus: false, class: "form-control" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Titulo</label>
                <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Titulo" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Sub Titulo</label>
                <%= f.text_field :subtitle, class: "form-control", placeholder: "Sub titulo" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso uno</label>
                <%= f.text_field :paso_one, class: "form-control", placeholder: "Paso uno" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso dos</label>
                <%= f.text_field :paso_two, class: "form-control", placeholder: "Paso dos" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paso tres</label>
                <%= f.text_field :paso_tree, class: "form-control", placeholder: "Paso tres" %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Servicio</label>
                  <%= f.collection_select(:service_id, Service.all, :id, :name, {:include_blank => 'Selecione un servicio'}) %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Paquete</label>
                  <%= f.collection_select(:bundle_id, Bundle.all, :id, :name, {:include_blank => 'Selecione un paquete'}) %>
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Activo</label>
                  <%= f.select(:visibility, [['SI', true], ['NO', false]]) %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Crear</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>