config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/admin/sign_in')
  #devise_for :admins
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    #get 'dashboard', controller: 'admin/user_permissions'
    get 'dashboard' => 'dashboard#index'
    resources :roles
    resources :services
    resources :pages
    scope '/service' do
      resources :categories
      resources :bundles
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
     #resources :roles

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  belongs_to :bundle
  belongs_to :page
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\Z/
  has_attached_file :imghover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :imghover, content_type: /\Aimage\/.*\Z/
  #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "0.png"
  #validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < ApplicationController
	layout 'admin'
	before_action :authenticate_admin!

	def index
		@services = Service.all.order(created_at: :desc)
		
	end

	def new
		@service = Service.new
	end

	def create
	  service = Service.new(service_params)
	  if service.save
      redirect_to admin_services_path
	  else
	    render 'new'
	  end
	end

	def edit
		@service = Service.find(params[:id])
	end

	def update
		@service = Service.find(params[:id])
	  if @service.update(service_params)
	    redirect_to admin_services_path
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @service = Service.find(params[:id])
	  @service.destroy
	  redirect_to admin_services_path
	end

  private
		def service_params
		  params.require(:service).permit(:name, :category_id, :bundle_id, :img, :imghover)
		end
end

app/views/admin/services/edit.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      editar paquete
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @service, url: {action: "update"}, html:{role: "form", multipart: true} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre del paquete" %>
              </div>
              <div class="form-group">
                <label>imagen</label>
                <%= image_tag @service.img.url(:thumb) %>
                <%= f.file_field :img, class: "form-control" %>
              </div>
              <div class="form-group">
                <label>imagen hover</label>
                <%= image_tag @service.imghover.url(:thumb) %>
                <%= f.file_field :imghover, class: "form-control" %>
              </div>
              <div class="form-group">
                <label>Categoria</label>
                <div class="form-group">
                  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
                </div>
              </div>
              <div class="form-group">
                <label>paquete</label>
                <div class="form-group">
                  <%= f.collection_select(:bundle_id, Bundle.all, :id, :name) %>
                </div>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/services/index.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Todos los servicios
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"></h3>
            <div class="box-tools">
              <div class="input-group" style="width: 150px;">
                <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div><!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tbody><tr>
                <th>Nombre</th>
                <th>Categoria</th>
                <th>Paquete</th>
                <th>Imagen</th>
                <th>Imagen hover</th>
                <th>Fecha de creación</th>
                <th>Acciones</th>
              </tr>
              <% @services.each do |service| %>
                <tr>
                  <td><%= service.name %></td>
                  <td><%= service.category.name %></td>
                  <% if service.bundle.nil? %>
                    <td></td>
                  <%else%>
                  <td><%= service.bundle.name %></td>
                  <%end%>
                  <td><%= image_tag service.img.url, style: "width:50px; height:50px;" %></td>
                  <td><%= image_tag service.imghover.url, style: "width:50px; height:50px;" %></td>
                  <td><%= service.created_at.httpdate.to_date %></td>
                  <td>
                    <%= link_to edit_admin_service_path(service) do %>
                      <i class="fa fa-edit"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to admin_service_path(service), method: :delete,
                   data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-remove"></i>
                   <%end%>
                   </td>
                  <!--td><span class="label label-success">Approved</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td-->
                </tr>
              <%end%>
            </tbody></table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/services/new.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Nuevo servicio
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @service, url: {action: "create"}, html:{role: "form", multipart: true} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre del paquete" %>
              </div>
              <div class="form-group">
                <label>imagen</label>
                <%= f.file_field :img, class: "form-control" %>
              </div>
              <div class="form-group">
                <label>imagen hover</label>
                <%= f.file_field :imghover, class: "form-control" %>
              </div>
              <div class="form-group">
                <label>Categoria</label>
                <div class="form-group">
                  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
                </div>
              </div>
              <div class="form-group">
                <label>paquete</label>
                <div class="form-group">
                  <%= f.collection_select(:bundle_id, Bundle.all, :id, :name) %>
                </div>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Crear</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>