config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'service/:url' => 'pages#show'
  get 'admin', to: redirect('/admin/sign_in')
  #devise_for :admins
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admin do
    #get 'dashboard', controller: 'admin/user_permissions'
    get 'dashboard' => 'dashboard#index'
    resources :roles
    resources :services
    resources :pages
    scope '/service' do
      resources :categories
      resources :bundles
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
     #resources :roles

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :services
	before_save :capitalize_name

	protected
	def capitalize_name
      self.name = self.name.capitalize
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	layout 'admin'
	before_action :authenticate_admin!

	def index
		@categories = Category.all.order(created_at: :desc)
		
	end
	def new
		@category = Category.new
	end

	def create
	  category = Category.new(category_params)
	  if category.save
      redirect_to admin_categories_path
	  else
	    render 'new'
	  end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
	  if @category.update(category_params)
	    redirect_to admin_categories_path
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @category = Category.find(params[:id])
	  @category.destroy
	  redirect_to admin_categories_path
	end

  private
		def category_params
		  params.require(:category).permit(:name, :price)
		end
end

app/views/admin/categories/edit.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Nueva Cataegoria
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @category, url: {action: "update"}, html:{role: "form"} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre de la categoria" %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/categories/index.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Todas las Cataegoria
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title"></h3>
            <div class="box-tools">
              <div class="input-group" style="width: 150px;">
                <input type="text" name="table_search" class="form-control input-sm pull-right" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
            </div>
          </div><!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <tbody><tr>
                <th>Nombre</th>
                <th>Fecha de creación</th>
                <th>Acciones</th>
              </tr>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <td><%= category.created_at.httpdate.to_date %></td>
                  <td>
                    <%= link_to edit_admin_category_path(category) do %>
                      <i class="fa fa-edit"></i>
                    <%end%>
                  </td>
                  <td>
                    <%= link_to admin_category_path(category), method: :delete,
                   data: { confirm: 'Are you sure?' } do %>
                      <i class="fa fa-remove"></i>
                   <%end%>
                   </td>
                  <!--td><span class="label label-success">Approved</span></td>
                  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td-->
                </tr>
              <%end%>
            </tbody></table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>

app/views/admin/categories/new.html.erb
<section class="content-wrapper">
  <section class="content-header">
    <h1>
      Nueva Cataegoria
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
      <li class="active">Here</li>
    </ol>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <!-- general form elements -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Nueva</h3>
          </div><!-- /.box-header -->
          <!-- form start -->
          <%= form_for @category, url: {action: "create"}, html:{role: "form"} do |f| %>
            <div class="box-body">
              <div class="form-group">
                <label for="exampleInputEmail1">Nombre</label>
                <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre de la categoria" %>
              </div>
            </div><!-- /.box-body -->
            <div class="box-footer">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          <%end%>
        </div><!-- /.box -->
      </div>
    </div>
  </section>
</section>